name: Preview Test Trigger

on:
  push:
    branches:
      - "*feature*"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "âœ… Trigger funktioniert: ${{ github.ref_name }}"
